#!/usr/bin/env python3
"""
修复Windows GBK编码不支持的Unicode字符
"""
import os
import re

def fix_unicode_in_file(file_path):
    """修复文件中的Unicode字符"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # 替换常见的Unicode字符
        replacements = {
            '✅': '[OK]',
            '❌': '[ERROR]',
            '📝': '[NOTE]',
            '🔨': '[BUILD]',
            '📤': '[SEND]',
            '📋': '[LIST]',
            '🔍': '[SEARCH]',
            '📊': '[CHART]',
            '📈': '[UP]',
            '📉': '[DOWN]',
            '⚠️': '[WARNING]',
            'ℹ️': '[INFO]',
            '🎯': '[TARGET]',
            '🚀': '[LAUNCH]',
            '💡': '[IDEA]',
            '🔧': '[TOOL]',
            '🗂️': '[FOLDER]',
            '📁': '[FOLDER]',
            '📂': '[FOLDER]',
            '📄': '[FILE]',
            '📃': '[FILE]',
            '📑': '[FILE]',
            '🗒️': '[NOTEBOOK]',
            '🏢': '[BUILDING]',
            '🏭': '[FACTORY]',
            '👥': '[TEAM]',
            '👤': '[PERSON]',
            '👥': '[GROUP]',
            '🌐': '[WEB]',
            '🔗': '[LINK]',
            '📞': '[PHONE]',
            '📧': '[EMAIL]',
            '📍': '[LOCATION]',
            '🏠': '[HOME]',
            '🏢': '[OFFICE]',
            '⏰': '[TIME]',
            '📅': '[DATE]',
            '🔄': '[REFRESH]',
            '🔁': '[REPEAT]',
            '➕': '[PLUS]',
            '➖': '[MINUS]',
            '✏️': '[EDIT]',
            '🗑️': '[DELETE]',
            '💾': '[SAVE]',
            '📥': '[DOWNLOAD]',
            '📤': '[UPLOAD]',
            '🔐': '[LOCK]',
            '🔓': '[UNLOCK]',
            '🔑': '[KEY]',
            '🚪': '[DOOR]',
            '🪟': '[WINDOW]',
            '🖥️': '[COMPUTER]',
            '📱': '[PHONE]',
            '⌨️': '[KEYBOARD]',
            '🖱️': '[MOUSE]',
            '🖨️': '[PRINTER]',
            '📠': '[FAX]',
            '📟': '[PHONE]',
            '📞': '[PHONE]',
            '📱': '[PHONE]',
            '📲': '[PHONE]',
            '⌚': '[WATCH]',
            '🕰️': '[CLOCK]',
            '⏲️': '[TIMER]',
            '⏱️': '[STOPWATCH]',
            '🧭': '[COMPASS]',
            '🗺️': '[MAP]',
            '🌍': '[EARTH]',
            '🌎': '[EARTH]',
            '🌏': '[EARTH]',
            '🌐': '[WEB]',
            '🗾': '[GLOBE]',
            '🔀': '[SHUFFLE]',
            '🔁': '[REPEAT]',
            '🔂': '[REPEAT]',
            '▶️': '[PLAY]',
            '⏸️': '[PAUSE]',
            '⏹️': '[STOP]',
            '⏺️': '[RECORD]',
            '⏯️': '[PLAY_PAUSE]',
            '🔀': '[SHUFFLE]',
            '🔁': '[REPEAT]',
            '🔂': '[REPEAT]',
            '⏭️': '[NEXT]',
            '⏮️': '[PREVIOUS]',
            '⏩': '[FAST_FORWARD]',
            '⏪': '[REWIND]',
            '⏫': '[FAST_FORWARD]',
            '⏬': '[REWIND]',
            '🔼': '[UP]',
            '🔽': '[DOWN]',
            '⏫': '[FAST_FORWARD]',
            '⏬': '[REWIND]',
            '➡️': '[RIGHT]',
            '⬅️': '[LEFT]',
            '⬆️': '[UP]',
            '⬇️': '[DOWN]',
            '↗️': '[UP_RIGHT]',
            '↘️': '[DOWN_RIGHT]',
            '↙️': '[DOWN_LEFT]',
            '↖️': '[UP_LEFT]',
            '↕️': '[UP_DOWN]',
            '↔️': '[LEFT_RIGHT]',
            '↪️': '[RIGHT_CURVED]',
            '↩️': '[LEFT_CURVED]',
            '⤴️': '[UP_CURVED]',
            '⤵️': '[DOWN_CURVED]',
            '🔃': '[REFRESH]',
            '🔄': '[SYNC]',
            '🔙': '[BACK]',
            '🔚': '[END]',
            '🔛': '[ON]',
            '🔜': '[SOON]',
            '🔝': '[TOP]',
            '🛐': '[PRAY]',
            '⚛️': '[ATOM]',
            '🕉️': '[OM]',
            '✡️': '[STAR_OF_DAVID]',
            '☸️': '[WHEEL]',
            '☯️': '[YIN_YANG]',
            '✝️': '[CROSS]',
            '☦️': '[ORTHODOX_CROSS]',
            '☪️': '[STAR_AND_CRESCENT]',
            '☮️': '[PEACE]',
            '🕎': '[MENORAH]',
            '🔯': '[DOTTED_SIX_POINTED_STAR]',
            '♈': '[ARIES]',
            '♉': '[TAURUS]',
            '♊': '[GEMINI]',
            '♋': '[CANCER]',
            '♌': '[LEO]',
            '♍': '[VIRGO]',
            '♎': '[LIBRA]',
            '♏': '[SCORPIO]',
            '♐': '[SAGITTARIUS]',
            '♑': '[CAPRICORN]',
            '♒': '[AQUARIUS]',
            '♓': '[PISCES]',
            '🆔': '[ID]',
            '⚠️': '[WARNING]',
            '🚸': '[CHILDREN_CROSSING]',
            '⛔': '[NO_ENTRY]',
            '🚫': '[PROHIBITED]',
            '🚳': '[NO_BICYCLES]',
            '🚭': '[NO_SMOKING]',
            '🚯': '[NO_LITTERING]',
            '🚱': '[NO_PEDESTRIANS]',
            '🚷': '[NO_MOTOR_VEHICLES]',
            '📵': '[NO_MOBILE_PHONES]',
            '🔞': '[NO_ONE_UNDER_18]',
            '☢️': '[RADIOACTIVE]',
            '☣️': '[BIOHAZARD]',
            '⬆️': '[UP_ARROW]',
            '↗️': '[UP_RIGHT_ARROW]',
            '➡️': '[RIGHT_ARROW]',
            '↘️': '[DOWN_RIGHT_ARROW]',
            '⬇️': '[DOWN_ARROW]',
            '↙️': '[DOWN_LEFT_ARROW]',
            '⬅️': '[LEFT_ARROW]',
            '↖️': '[UP_LEFT_ARROW]',
            '↕️': '[UP_DOWN_ARROW]',
            '↔️': '[LEFT_RIGHT_ARROW]',
            '↩️': '[RIGHT_ARROW_CURVING_LEFT]',
            '↪️': '[LEFT_ARROW_CURVING_RIGHT]',
            '⤴️': '[RIGHT_ARROW_CURVING_UP]',
            '⤵️': '[RIGHT_ARROW_CURVING_DOWN]',
            '🔃': '[CLOCKWISE_VERTICAL_ARROWS]',
            '🔄': '[CLOCKWISE_ARROWS]',
            '🔙': '[BACK_ARROW]',
            '🔚': '[END_ARROW]',
            '🔛': '[ON_ARROW]',
            '🔜': '[SOON_ARROW]',
            '🔝': '[TOP_ARROW]',
            '🛐': '[PLACE_OF_WORSHIP]',
            '⚛️': '[ATOM_SYMBOL]',
            '✅': '[WHITE_CHECK_MARK]',
            '☑️': '[BALLOT_BOX_WITH_CHECK]',
            '✔️': '[HEAVY_CHECK_MARK]',
            '✖️': '[HEAVY_MULTIPLICATION_X]',
            '❌': '[CROSS_MARK]',
            '❎': '[NEGATIVE_SQUARED_CROSS_MARK]',
            '➕': '[HEAVY_PLUS_SIGN]',
            '➖': '[HEAVY_MINUS_SIGN]',
            '➗': '[HEAVY_DIVISION_SIGN]',
            '✳️': '[HEAVY_EIGHT_POINTED_STAR]',
            '✴️': '[EIGHT_POINTED_STAR]',
            '❇️': '[SPARKLE]',
            '‼️': '[DOUBLE_EXCLAMATION_MARK]',
            '⁉️': '[EXCLAMATION_QUESTION_MARK]',
            '❓': '[BLACK_QUESTION_MARK]',
            '❔': '[WHITE_QUESTION_MARK]',
            '❕': '[WHITE_EXCLAMATION_MARK]',
            '❗': '[HEAVY_EXCLAMATION_MARK]',
            '❚': '[HEAVY_EXCLAMATION_MARK_ORNAMENT]',
            '❛': '[HEAVY_LEFT-POINTING_ANGLE_QUOTATION_MARK]',
            '❜': '[HEAVY_RIGHT-POINTING_ANGLE_QUOTATION_MARK]',
            '❝': '[LEFT_DOUBLE_QUOTATION_MARK]',
            '❞': '[RIGHT_DOUBLE_QUOTATION_MARK]',
            '❟': '[HEAVY_LOW_SINGLE_COMMA_QUOTATION_MARK]',
            '❠': '[HEAVY_LOW_DOUBLE_COMMA_QUOTATION_MARK]',
            '❡': '[HEAVY_LOW_SINGLE_TURNED_COMMA_QUOTATION_MARK]',
            '❢': '[HEAVY_LOW_DOUBLE_TURNED_COMMA_QUOTATION_MARK]',
            '❣': '[HEAVY_BLACK_HEART]',
            '❤️': '[HEAVY_BLACK_HEART]',
            '❥': '[ROTATED_HEAVY_BLACK_HEART_BULLET]',
            '❦️': '[FLORAL_HEART]',
            '❧': '[ROTATED_HEAVY_BLACK_HEART_BULLET_WITH_FLOWER]',
            '❨': '[HEAVY_BLACK_HEART]',
            '❩': '[HEAVY_BLACK_HEART]',
            '❪': '[HEAVY_BLACK_HEART]',
            '❫': '[HEAVY_BLACK_HEART]',
            '❬': '[HEAVY_BLACK_HEART]',
            '❭': '[HEAVY_BLACK_HEART]',
            '❮': '[HEAVY_BLACK_HEART]',
            '❯': '[HEAVY_BLACK_HEART]',
            '❰': '[HEAVY_BLACK_HEART]',
            '❱': '[HEAVY_BLACK_HEART]',
            '❲': '[HEAVY_BLACK_HEART]',
            '❳': '[HEAVY_BLACK_HEART]',
            '❴': '[HEAVY_BLACK_HEART]',
            '❵': '[HEAVY_BLACK_HEART]',
            '❶': '[CIRCLED_NUMBER_ONE]',
            '❷': '[CIRCLED_NUMBER_TWO]',
            '❸': '[CIRCLED_NUMBER_THREE]',
            '❹': '[CIRCLED_NUMBER_FOUR]',
            '❺': '[CIRCLED_NUMBER_FIVE]',
            '❻': '[CIRCLED_NUMBER_SIX]',
            '❽': '[CIRCLED_NUMBER_SEVEN]',
            '❾': '[CIRCLED_NUMBER_EIGHT]',
            '❿': '[CIRCLED_NUMBER_NINE]',
            '➀': '[NEGATIVE_CIRCLED_NUMBER_ONE]',
            '➁': '[NEGATIVE_CIRCLED_NUMBER_TWO]',
            '➂': '[NEGATIVE_CIRCLED_NUMBER_THREE]',
            '➃': '[NEGATIVE_CIRCLED_NUMBER_FOUR]',
            '➄': '[NEGATIVE_CIRCLED_NUMBER_FIVE]',
            '➅': '[NEGATIVE_CIRCLED_NUMBER_SIX]',
            '➆': '[NEGATIVE_CIRCLED_NUMBER_SEVEN]',
            '➇': '[NEGATIVE_CIRCLED_NUMBER_EIGHT]',
            '➈': '[NEGATIVE_CIRCLED_NUMBER_NINE]',
            '➉': '[NEGATIVE_CIRCLED_NUMBER_TEN]',
            '➊': '[KEYCAP_TEN]',
            '➋': '[KEYCAP_TEN]',
            '➌': '[KEYCAP_TEN]',
            '➍': '[KEYCAP_TEN]',
            '➎': '[KEYCAP_TEN]',
            '➏': '[KEYCAP_TEN]',
            '➐': '[KEYCAP_TEN]',
            '➑': '[KEYCAP_TEN]',
            '➒': '[KEYCAP_TEN]',
            '➓': '[KEYCAP_TEN]',
            '➔': '[KEYCAP_TEN]',
            '➕': '[HEAVY_PLUS_SIGN]',
            '➖': '[HEAVY_MINUS_SIGN]',
            '➗': '[HEAVY_DIVISION_SIGN]',
            '➘': '[HEAVY_DIVISION_SIGN]',
            '➙': '[HEAVY_DIVISION_SIGN]',
            '➚': '[HEAVY_DIVISION_SIGN]',
            '➛': '[HEAVY_DIVISION_SIGN]',
            '➜': '[HEAVY_DIVISION_SIGN]',
            '➝': '[HEAVY_DIVISION_SIGN]',
            '➞': '[HEAVY_DIVISION_SIGN]',
            '➟': '[HEAVY_DIVISION_SIGN]',
            '➠': '[HEAVY_DIVISION_SIGN]',
            '➡': '[HEAVY_DIVISION_SIGN]',
            '➢': '[HEAVY_DIVISION_SIGN]',
            '➣': '[HEAVY_DIVISION_SIGN]',
            '➤': '[HEAVY_DIVISION_SIGN]',
            '➥': '[HEAVY_DIVISION_SIGN]',
            '➦': '[HEAVY_DIVISION_SIGN]',
            '➧': '[HEAVY_DIVISION_SIGN]',
            '➨': '[HEAVY_DIVISION_SIGN]',
            '➩': '[HEAVY_DIVISION_SIGN]',
            '➪': '[HEAVY_DIVISION_SIGN]',
            '➫': '[HEAVY_DIVISION_SIGN]',
            '➬': '[HEAVY_DIVISION_SIGN]',
            '➭': '[HEAVY_DIVISION_SIGN]',
            '➮': '[HEAVY_DIVISION_SIGN]',
            '➯': '[HEAVY_DIVISION_SIGN]',
            '➰': '[HEAVY_DIVISION_SIGN]',
            '➱': '[HEAVY_DIVISION_SIGN]',
            '➲': '[HEAVY_DIVISION_SIGN]',
            '➳': '[HEAVY_DIVISION_SIGN]',
            '➴': '[HEAVY_DIVISION_SIGN]',
            '➵': '[HEAVY_DIVISION_SIGN]',
            '➶': '[HEAVY_DIVISION_SIGN]',
            '➷': '[HEAVY_DIVISION_SIGN]',
            '➸': '[HEAVY_DIVISION_SIGN]',
            '➹': '[HEAVY_DIVISION_SIGN]',
            '➺': '[HEAVY_DIVISION_SIGN]',
            '➻': '[HEAVY_DIVISION_SIGN]',
            '➼': '[HEAVY_DIVISION_SIGN]',
            '➽': '[HEAVY_DIVISION_SIGN]',
            '➾': '[HEAVY_DIVISION_SIGN]',
            '➿': '[HEAVY_DIVISION_SIGN]',
        }
        
        # 应用替换
        modified = False
        for unicode_char, replacement in replacements.items():
            if unicode_char in content:
                content = content.replace(unicode_char, replacement)
                modified = True
                print(f"Replaced {unicode_char} with {replacement} in {file_path}")
        
        if modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Fixed Unicode characters in {file_path}")
            return True
        return False
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return False

def fix_unicode_in_directory(directory):
    """修复目录中所有Python文件的Unicode字符"""
    fixed_count = 0
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.py'):
                file_path = os.path.join(root, file)
                if fix_unicode_in_file(file_path):
                    fixed_count += 1
    print(f"Fixed Unicode characters in {fixed_count} files")

if __name__ == "__main__":
    # 修复app目录中的所有Python文件
    fix_unicode_in_directory("backend/app")